-- Auth activity logs.
-- Run this in the Supabase SQL editor before deploying log-auth-activity.

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and coalesce(status, 'active') = 'active'
  );
$$;

grant execute on function public.is_admin() to authenticated;

create table if not exists public.auth_activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null,
  ip_address inet,
  country text,
  region text,
  city text,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  timezone text,
  platform text,
  app_version text,
  device_name text,
  os_name text,
  os_version text,
  user_agent text,
  created_at timestamptz not null default now()
);

delete from public.auth_activity_logs
where event_type = 'session_start'
   or created_at < now() - interval '90 days';

alter table public.auth_activity_logs
drop constraint if exists auth_activity_logs_event_type_check;

alter table public.auth_activity_logs
add constraint auth_activity_logs_event_type_check
check (event_type in ('login', 'logout'));

create index if not exists auth_activity_logs_user_created_idx
on public.auth_activity_logs (user_id, created_at desc);

create index if not exists auth_activity_logs_created_idx
on public.auth_activity_logs (created_at desc);

alter table public.auth_activity_logs enable row level security;

drop policy if exists auth_activity_logs_select_own_or_admin
on public.auth_activity_logs;

create policy auth_activity_logs_select_own_or_admin
on public.auth_activity_logs
for select
using (user_id = auth.uid() or public.is_admin());

drop policy if exists auth_activity_logs_insert_own
on public.auth_activity_logs;

create policy auth_activity_logs_insert_own
on public.auth_activity_logs
for insert
with check (user_id = auth.uid());

grant select, insert on public.auth_activity_logs to authenticated;
grant usage, select on sequence public.auth_activity_logs_id_seq to authenticated;

create or replace function public.admin_cleanup_auth_activity_logs()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted_count integer := 0;
begin
  if not public.is_admin() then
    raise exception '관리자만 접속기록을 정리할 수 있습니다.';
  end if;

  delete from public.auth_activity_logs
  where created_at < now() - interval '90 days';

  get diagnostics v_deleted_count = row_count;
  return v_deleted_count;
end;
$$;

revoke all on function public.admin_cleanup_auth_activity_logs() from public;
grant execute on function public.admin_cleanup_auth_activity_logs() to authenticated;

select pg_notify('pgrst', 'reload schema');
