-- Store commerce foundation: store product fields, store profile settings,
-- basic interaction stats, subscriptions, and estimate requests.

alter table public.profiles
  add column if not exists store_intro text,
  add column if not exists store_notice text,
  add column if not exists store_business_hours text,
  add column if not exists store_accepts_inquiries boolean not null default true,
  add column if not exists store_today_available boolean not null default false,
  add column if not exists store_card_available boolean not null default false,
  add column if not exists store_cash_receipt_available boolean not null default false,
  add column if not exists store_tax_invoice_available boolean not null default false;

alter table public.listings
  add column if not exists seller_type text not null default 'personal',
  add column if not exists store_user_id uuid references public.profiles(id) on delete set null,
  add column if not exists is_store_product boolean not null default false,
  add column if not exists pickup_available boolean not null default true,
  add column if not exists delivery_available boolean not null default false,
  add column if not exists card_available boolean not null default false,
  add column if not exists cash_receipt_available boolean not null default false,
  add column if not exists tax_invoice_available boolean not null default false,
  add column if not exists vat_included boolean not null default true;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.listings'::regclass
      and conname = 'listings_seller_type_check'
  ) then
    alter table public.listings
      add constraint listings_seller_type_check
      check (seller_type in ('personal', 'store'));
  end if;
end $$;

update public.listings l
set
  seller_type = 'store',
  store_user_id = l.author_id,
  is_store_product = true
from public.profiles p
where l.author_id = p.id
  and p.user_type = 'store'
  and coalesce(p.business_verified, false)
  and l.seller_type = 'personal';

create index if not exists listings_store_user_status_idx
on public.listings (store_user_id, status, created_at desc)
where store_user_id is not null;

create table if not exists public.store_interactions (
  id bigint generated by default as identity primary key,
  store_user_id uuid references public.profiles(id) on delete cascade,
  listing_id bigint references public.listings(id) on delete set null,
  actor_id uuid references public.profiles(id) on delete set null,
  interaction_type text not null,
  created_at timestamptz not null default now()
);

alter table public.store_interactions enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.store_interactions'::regclass
      and conname = 'store_interactions_type_check'
  ) then
    alter table public.store_interactions
      add constraint store_interactions_type_check
      check (interaction_type in ('chat', 'phone', 'directions', 'store_view', 'product_view'));
  end if;
end $$;

drop policy if exists store_interactions_insert_authenticated on public.store_interactions;
create policy store_interactions_insert_authenticated
on public.store_interactions
for insert
with check (auth.uid() is not null);

drop policy if exists store_interactions_select_own_store on public.store_interactions;
create policy store_interactions_select_own_store
on public.store_interactions
for select
using (auth.uid() = store_user_id or public.is_admin());

create index if not exists store_interactions_store_created_idx
on public.store_interactions (store_user_id, created_at desc);

create table if not exists public.store_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan text not null default 'free',
  status text not null default 'active',
  started_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id)
);

alter table public.store_subscriptions enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.store_subscriptions'::regclass
      and conname = 'store_subscriptions_plan_check'
  ) then
    alter table public.store_subscriptions
      add constraint store_subscriptions_plan_check
      check (plan in ('free', 'premium', 'local_ad', 'partner'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.store_subscriptions'::regclass
      and conname = 'store_subscriptions_status_check'
  ) then
    alter table public.store_subscriptions
      add constraint store_subscriptions_status_check
      check (status in ('active', 'expired', 'canceled'));
  end if;
end $$;

drop policy if exists store_subscriptions_select_own_or_admin on public.store_subscriptions;
create policy store_subscriptions_select_own_or_admin
on public.store_subscriptions
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists store_subscriptions_admin_all on public.store_subscriptions;
create policy store_subscriptions_admin_all
on public.store_subscriptions
for all
using (public.is_admin())
with check (public.is_admin());

create table if not exists public.estimate_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  category text not null,
  region text,
  address text,
  budget text,
  desired_date date,
  title text not null,
  description text,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.estimate_requests enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.estimate_requests'::regclass
      and conname = 'estimate_requests_status_check'
  ) then
    alter table public.estimate_requests
      add constraint estimate_requests_status_check
      check (status in ('open', 'contacted', 'closed', 'hidden'));
  end if;
end $$;

drop policy if exists estimate_requests_select_own_or_admin on public.estimate_requests;
create policy estimate_requests_select_own_or_admin
on public.estimate_requests
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists estimate_requests_insert_own on public.estimate_requests;
create policy estimate_requests_insert_own
on public.estimate_requests
for insert
with check (auth.uid() = user_id);

drop policy if exists estimate_requests_update_own_or_admin on public.estimate_requests;
create policy estimate_requests_update_own_or_admin
on public.estimate_requests
for update
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

select pg_notify('pgrst', 'reload schema');
