-- Store categories, estimate routing to a preferred store, and review images.

alter table public.profiles
  add column if not exists store_category text;

create index if not exists profiles_verified_store_category_idx
on public.profiles (store_category, display_name)
where user_type = 'store'
  and coalesce(business_verified, false);

alter table public.estimate_requests
  add column if not exists preferred_store_user_id uuid references public.profiles(id) on delete set null,
  add column if not exists assigned_store_user_id uuid references public.profiles(id) on delete set null,
  add column if not exists routing_status text not null default 'admin_pending',
  add column if not exists fallback_destination text not null default 'designwish';

alter table public.estimate_requests
  drop constraint if exists estimate_requests_routing_status_check;

alter table public.estimate_requests
  add constraint estimate_requests_routing_status_check
  check (routing_status in ('store_selected', 'admin_pending', 'admin_assigned', 'designwish'));

create index if not exists estimate_requests_preferred_store_idx
on public.estimate_requests (preferred_store_user_id, created_at desc)
where preferred_store_user_id is not null;

create index if not exists estimate_requests_assigned_store_idx
on public.estimate_requests (assigned_store_user_id, created_at desc)
where assigned_store_user_id is not null;

create or replace function public.store_can_access_estimate_request(p_request_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.estimate_requests er
    join public.profiles p on p.id = auth.uid()
    where er.id = p_request_id
      and p.user_type = 'store'
      and coalesce(p.business_verified, false)
      and coalesce(p.store_accepts_inquiries, true)
      and coalesce(p.status, 'active') = 'active'
      and (
        er.preferred_store_user_id = auth.uid()
        or er.assigned_store_user_id = auth.uid()
      )
  );
$$;

grant execute on function public.store_can_access_estimate_request(bigint) to authenticated;

drop policy if exists estimate_requests_select_participants on public.estimate_requests;
create policy estimate_requests_select_participants
on public.estimate_requests
for select
using (
  auth.uid() = user_id
  or public.is_admin()
  or public.store_can_access_estimate_request(id)
);

drop policy if exists estimate_request_images_select_participants on public.estimate_request_images;
create policy estimate_request_images_select_participants
on public.estimate_request_images
for select
using (
  exists (
    select 1
    from public.estimate_requests er
    where er.id = estimate_request_id
      and (
        er.user_id = auth.uid()
        or public.is_admin()
        or public.store_can_access_estimate_request(er.id)
      )
  )
);

create or replace function public.create_estimate_store_status_for_selected_store()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_store_user_id uuid;
begin
  v_store_user_id := coalesce(new.assigned_store_user_id, new.preferred_store_user_id);

  if v_store_user_id is null then
    return new;
  end if;

  insert into public.estimate_request_store_statuses (
    estimate_request_id,
    store_user_id,
    status
  )
  values (
    new.id,
    v_store_user_id,
    'new'
  )
  on conflict (estimate_request_id, store_user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists estimate_requests_create_selected_store_status on public.estimate_requests;
create trigger estimate_requests_create_selected_store_status
after insert or update of preferred_store_user_id, assigned_store_user_id
on public.estimate_requests
for each row execute function public.create_estimate_store_status_for_selected_store();

create table if not exists public.review_images (
  id bigint generated by default as identity primary key,
  review_id uuid not null references public.reviews(id) on delete cascade,
  image_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.review_images enable row level security;

create index if not exists review_images_review_idx
on public.review_images (review_id, sort_order);

drop policy if exists review_images_select_visible on public.review_images;
create policy review_images_select_visible
on public.review_images
for select
using (
  exists (
    select 1
    from public.reviews r
    left join public.profiles target_profile on target_profile.id = r.target_user_id
    where r.id = review_id
      and (
        r.reviewer_id = auth.uid()
        or r.target_user_id = auth.uid()
        or public.is_admin()
        or (
          target_profile.user_type = 'store'
          and coalesce(target_profile.business_verified, false)
        )
      )
  )
);

drop policy if exists review_images_insert_reviewer on public.review_images;
create policy review_images_insert_reviewer
on public.review_images
for insert
with check (
  exists (
    select 1
    from public.reviews r
    where r.id = review_id
      and r.reviewer_id = auth.uid()
  )
);

drop policy if exists reviews_select_verified_store_targets on public.reviews;
create policy reviews_select_verified_store_targets
on public.reviews
for select
using (
  exists (
    select 1
    from public.profiles p
    where p.id = target_user_id
      and p.user_type = 'store'
      and coalesce(p.business_verified, false)
  )
);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'review-images',
  'review-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public review images are readable" on storage.objects;
drop policy if exists "Users can upload own review images" on storage.objects;
drop policy if exists "Users can delete own review images" on storage.objects;

create policy "Public review images are readable"
on storage.objects
for select
using (bucket_id = 'review-images');

create policy "Users can upload own review images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'review-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can delete own review images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'review-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

grant select, insert on public.review_images to authenticated;
grant usage, select on sequence public.review_images_id_seq to authenticated;

select pg_notify('pgrst', 'reload schema');
