-- Estimate requests and store-side customer/quote management.

create or replace function public.is_verified_store_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and user_type = 'store'
      and coalesce(business_verified, false)
      and coalesce(store_accepts_inquiries, true)
      and coalesce(status, 'active') = 'active'
  );
$$;

grant execute on function public.is_verified_store_user() to authenticated;

create table if not exists public.estimate_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  category text not null,
  region text,
  address text,
  budget text,
  desired_date date,
  title text not null,
  description text,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.estimate_requests
  add column if not exists preferred_contact text,
  add column if not exists admin_note text;

alter table public.estimate_requests enable row level security;

alter table public.estimate_requests
  drop constraint if exists estimate_requests_status_check;

alter table public.estimate_requests
  add constraint estimate_requests_status_check
  check (status in ('open', 'contacted', 'closed', 'hidden'));

create index if not exists estimate_requests_created_idx
on public.estimate_requests (created_at desc);

create index if not exists estimate_requests_category_region_idx
on public.estimate_requests (category, region);

drop policy if exists estimate_requests_select_own_or_admin on public.estimate_requests;
drop policy if exists estimate_requests_select_participants on public.estimate_requests;
create policy estimate_requests_select_participants
on public.estimate_requests
for select
using (
  auth.uid() = user_id
  or public.is_admin()
  or public.is_verified_store_user()
);

drop policy if exists estimate_requests_insert_own on public.estimate_requests;
create policy estimate_requests_insert_own
on public.estimate_requests
for insert
with check (auth.uid() = user_id);

drop policy if exists estimate_requests_update_own_or_admin on public.estimate_requests;
create policy estimate_requests_update_own_or_admin
on public.estimate_requests
for update
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

create table if not exists public.estimate_request_images (
  id bigint generated by default as identity primary key,
  estimate_request_id bigint not null references public.estimate_requests(id) on delete cascade,
  image_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.estimate_request_images enable row level security;

create index if not exists estimate_request_images_request_idx
on public.estimate_request_images (estimate_request_id, sort_order);

drop policy if exists estimate_request_images_select_participants on public.estimate_request_images;
create policy estimate_request_images_select_participants
on public.estimate_request_images
for select
using (
  exists (
    select 1
    from public.estimate_requests er
    where er.id = estimate_request_id
      and (
        er.user_id = auth.uid()
        or public.is_admin()
        or public.is_verified_store_user()
      )
  )
);

drop policy if exists estimate_request_images_insert_owner on public.estimate_request_images;
create policy estimate_request_images_insert_owner
on public.estimate_request_images
for insert
with check (
  exists (
    select 1
    from public.estimate_requests er
    where er.id = estimate_request_id
      and er.user_id = auth.uid()
  )
);

drop policy if exists estimate_request_images_delete_owner_or_admin on public.estimate_request_images;
create policy estimate_request_images_delete_owner_or_admin
on public.estimate_request_images
for delete
using (
  public.is_admin()
  or exists (
    select 1
    from public.estimate_requests er
    where er.id = estimate_request_id
      and er.user_id = auth.uid()
  )
);

create table if not exists public.estimate_request_store_statuses (
  id bigint generated by default as identity primary key,
  estimate_request_id bigint not null references public.estimate_requests(id) on delete cascade,
  store_user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'new',
  memo text,
  last_contacted_at timestamptz,
  next_follow_up_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(estimate_request_id, store_user_id)
);

alter table public.estimate_request_store_statuses enable row level security;

alter table public.estimate_request_store_statuses
  drop constraint if exists estimate_request_store_statuses_status_check;

alter table public.estimate_request_store_statuses
  add constraint estimate_request_store_statuses_status_check
  check (status in ('new', 'consulting', 'estimating', 'contracted', 'construction', 'completed', 'closed'));

create index if not exists estimate_request_store_statuses_store_idx
on public.estimate_request_store_statuses (store_user_id, status, updated_at desc);

drop policy if exists estimate_request_store_statuses_select_participants on public.estimate_request_store_statuses;
create policy estimate_request_store_statuses_select_participants
on public.estimate_request_store_statuses
for select
using (
  auth.uid() = store_user_id
  or public.is_admin()
  or exists (
    select 1
    from public.estimate_requests er
    where er.id = estimate_request_id
      and er.user_id = auth.uid()
  )
);

drop policy if exists estimate_request_store_statuses_insert_store on public.estimate_request_store_statuses;
create policy estimate_request_store_statuses_insert_store
on public.estimate_request_store_statuses
for insert
with check (
  auth.uid() = store_user_id
  and public.is_verified_store_user()
);

drop policy if exists estimate_request_store_statuses_update_store on public.estimate_request_store_statuses;
create policy estimate_request_store_statuses_update_store
on public.estimate_request_store_statuses
for update
using (auth.uid() = store_user_id or public.is_admin())
with check (auth.uid() = store_user_id or public.is_admin());

create table if not exists public.estimate_quotes (
  id bigint generated by default as identity primary key,
  estimate_request_id bigint not null references public.estimate_requests(id) on delete cascade,
  store_user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default '견적서',
  status text not null default 'draft',
  labor_cost integer not null default 0,
  material_cost integer not null default 0,
  additional_cost integer not null default 0,
  total_amount integer not null default 0,
  deposit_amount integer not null default 0,
  progress_amount integer not null default 0,
  final_amount integer not null default 0,
  additional_work text,
  memo text,
  pdf_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(estimate_request_id, store_user_id)
);

alter table public.estimate_quotes enable row level security;

alter table public.estimate_quotes
  drop constraint if exists estimate_quotes_status_check;

alter table public.estimate_quotes
  add constraint estimate_quotes_status_check
  check (status in ('draft', 'sent', 'accepted', 'rejected'));

create index if not exists estimate_quotes_store_idx
on public.estimate_quotes (store_user_id, updated_at desc);

drop policy if exists estimate_quotes_select_participants on public.estimate_quotes;
create policy estimate_quotes_select_participants
on public.estimate_quotes
for select
using (
  auth.uid() = store_user_id
  or public.is_admin()
  or exists (
    select 1
    from public.estimate_requests er
    where er.id = estimate_request_id
      and er.user_id = auth.uid()
  )
);

drop policy if exists estimate_quotes_insert_store on public.estimate_quotes;
create policy estimate_quotes_insert_store
on public.estimate_quotes
for insert
with check (
  auth.uid() = store_user_id
  and public.is_verified_store_user()
);

drop policy if exists estimate_quotes_update_store on public.estimate_quotes;
create policy estimate_quotes_update_store
on public.estimate_quotes
for update
using (auth.uid() = store_user_id or public.is_admin())
with check (auth.uid() = store_user_id or public.is_admin());

create table if not exists public.estimate_quote_attachments (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.estimate_quotes(id) on delete cascade,
  file_path text not null,
  file_name text,
  file_type text,
  created_at timestamptz not null default now()
);

alter table public.estimate_quote_attachments enable row level security;

drop policy if exists estimate_quote_attachments_select_participants on public.estimate_quote_attachments;
create policy estimate_quote_attachments_select_participants
on public.estimate_quote_attachments
for select
using (
  exists (
    select 1
    from public.estimate_quotes q
    join public.estimate_requests er on er.id = q.estimate_request_id
    where q.id = quote_id
      and (
        q.store_user_id = auth.uid()
        or er.user_id = auth.uid()
        or public.is_admin()
      )
  )
);

drop policy if exists estimate_quote_attachments_insert_store on public.estimate_quote_attachments;
create policy estimate_quote_attachments_insert_store
on public.estimate_quote_attachments
for insert
with check (
  exists (
    select 1
    from public.estimate_quotes q
    where q.id = quote_id
      and q.store_user_id = auth.uid()
  )
);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'estimate-images',
  'estimate-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public estimate images are readable" on storage.objects;
drop policy if exists "Users can upload own estimate images" on storage.objects;
drop policy if exists "Users can delete own estimate images" on storage.objects;

create policy "Public estimate images are readable"
on storage.objects
for select
using (bucket_id = 'estimate-images');

create policy "Users can upload own estimate images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'estimate-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users can delete own estimate images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'estimate-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

grant select, insert, update on public.estimate_requests to authenticated;
grant select, insert, delete on public.estimate_request_images to authenticated;
grant select, insert, update on public.estimate_request_store_statuses to authenticated;
grant select, insert, update on public.estimate_quotes to authenticated;
grant select, insert on public.estimate_quote_attachments to authenticated;

grant usage, select on sequence public.estimate_requests_id_seq to authenticated;
grant usage, select on sequence public.estimate_request_images_id_seq to authenticated;
grant usage, select on sequence public.estimate_request_store_statuses_id_seq to authenticated;
grant usage, select on sequence public.estimate_quotes_id_seq to authenticated;
grant usage, select on sequence public.estimate_quote_attachments_id_seq to authenticated;

select pg_notify('pgrst', 'reload schema');
